test "formatted numbers":
	set {_num1} to numberFormat(123456789)
	assert {_num1} = "123,456,789" with "default number format failed ##1"

	set {_num2} to numberFormat(1234567)
	assert {_num2} = "1,234,567" with "default number format failed ##2"

	set {_num3} to numberFormat(12345678, "##,##.00")
	assert {_num3} = "1,2,3,4,5,6,7,8.00" with "custom number format failed ##1"

	set {_cFormat} to "####,####"
	set {_num4} to numberFormat(12345678, {_cFormat})
	assert {_num4} = "12,34,56,78" with "custom number format failed ##2"

	set {_cFormat2} to "##,.##"
	set {_num5} to numberFormat(12345678, {_cFormat2})
	assert {_num5} is not set with "custom number format failed ##3"
