test "formatted numbers":
	set {_num1} to formatted 123456789
	assert {_num1} = "123,456,789" with "default number format failed ##1"

	set {_num2} to 1234567 formatted human-readable
	assert {_num2} = "1,234,567" with "default number format failed ##2"

	set {_num3} to formatted 12345678 as "##,##.00"
	assert {_num3} = "1,2,3,4,5,6,7,8.00" with "custom number format failed ##1"

	set {_cFormat} to "####,####"
	set {_num4} to formatted 12345678 as {_cFormat}
	assert {_num4} = "12,34,56,78" with "custom number format failed ##2"

	set {_cFormat2} to "i"
	set {_num4} to formatted 12345678 as {_cFormat2}
	assert {_num4} is not set with "custom number format failed ##3"
