test "item amount of itemstack":
	set event-block to chest
	add 10 stone to inventory of event-block
	set {_item} to slot 0 of inventory of event-block
	assert item amount of {_item} is 10 with "Amount of itemstack is not 10 %item amount of {_item}%"
	remove 1 from item amount of {_item}
	assert item amount of {_item} is 9 with "Amount of itemstack is not 9"
	set event-block to air

test "item amount of itemtype":
	set {_item} to 10 stone
	set {_amount} to item amount of {_item}
	assert item amount of {_item} is 10 with "Amount of itemtype is not 10%"
	remove 1 from item amount of {_item}
	assert item amount of {_item} is 9 with "Amount of itemtype is not 9"

test "item amount of slot":
	set event-block to chest
	add 10 stone to inventory of block at {_loc}
	assert item amount of (slot 0 of inventory of block at {_loc}) is 10 with "Amount of slot is not 10"
	remove 1 from item amount of (slot 0 of inventory of block at {_loc})
	assert item amount of (slot 0 of inventory of block at {_loc}) is 9 with "Amount of slot is not 9"
	set event-block to air