test "77449 - Tag Lookup Only does Minecraft":
	register an item tag named "my_favorite_blocks" using oak log, stone, and podzol
	assert tag "my_favorite_blocks" is tag "skript:my_favorite_blocks" with "Tag lookup didn't find a skript tag ""helmets"" namespace"
	assert tag "helmets" is tag "paper:helmets" with "Tag lookup didn't find a paper tag ""helmets"" namespace"
	assert tag "enchantable/sword" is tag "minecraft:enchantable/sword" with "Tag lookup didn't find a minecraft tag ""enchantable/sword"" namespace"
