test "can't compare bookshelf with block":
	set {_type} to block at test location

	set block at test location to bookshelf
	assert block at test location is bookshelf

	set block at test location to chiseled bookshelf
	assert block at test location is chiseled bookshelf

	set block at test location to {_type}

test "can't compare bookshelf with block" when minecraft version is not below "1.20.0":
	set {_type} to block at test location
	set block at test location to decorated pot
	assert block at test location is decorated pot
	set block at test location to {_type}