local function test(x: object) -> object:
    return {_x}

local function test_same(minecraft: object) -> object:
    return {_minecraft}

test "fully qualified names and named argument functions conflict":
    assert test(minecraft:plains) is minecraft:plains
    assert test(minecraft:stone) is minecraft:stone
    assert test(minecraft:stone) is stone
    assert test(x: minecraft:stone) is minecraft:stone
    assert test(x: minecraft:stone) is stone
    parse:
        assert test(minecraft: stone) is minecraft:stone
    assert last parse logs are set

    assert test_same(stone) is minecraft:stone
    assert test_same(minecraft:stone) is minecraft:stone
    assert test_same(minecraft:minecraft:stone) is minecraft:stone
    assert test_same(minecraft:minecraft:plains) is minecraft:plains

    parse:
        assert test(minecraft: minecraft: stone) is minecraft:stone
    assert last parse logs are set
