inputs:
  docs_deploy_key: 
     description: "Deploy key for the skript-docs repo"
     required: true

name: Setup documentation environment
env:
    DOCS_DEPLOY_KEY: ${{ github.event.inputs.docs_deploy_key }}
run: |
  eval `ssh-agent`
  DOC_DIR="${GITHUB_WORKSPACE}/skript-docs/docs/nightly/${GITHUB_REF#refs/heads/}"
  rm -r ${DOC_DIR}/* || true
  echo "DOC_DIR=${DOC_DIR}" >> $GITHUB_ENV
  echo "SKRIPT_DOCS_TEMPLATE_DIR=${GITHUB_WORKSPACE}/skript-docs/doc-templates" >> $GITHUB_ENV
  echo "SKRIPT_DOCS_OUTPUT_DIR=${DOC_DIR}/" >> $GITHUB_ENV
  echo "$DOCS_DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir ~/.ssh
  ssh-keyscan www.github.com >> ~/.ssh/known_hosts
