on script load:
	ensure junit test "org.skriptlang.skript.test.tests.regression.AsyncEvents_5689" completes "async chat"

on chat:
	junit test is "org.skriptlang.skript.test.tests.regression.AsyncEvents_5689"

	# Attempting to throw an exception
	set {_block} to type of block at spawn of "world"
	set block at spawn of "world" to stone
	set block at spawn of "world" to {_block}
	execute console command "command doesn't exist"
	wait a tick
	complete objective "async chat" for junit test "org.skriptlang.skript.test.tests.regression.AsyncEvents_5689"
