test "Server Tick State Expressions" when running minecraft "1.20.4":
	# Test if server is normal
	assert server's tick state is normal with "Server tick state is not normal"

	freeze the server
	assert server's tick state is frozen with "Server tick state is not frozen"

	# Step the server and test
	make the server step for 5 seconds
	assert server's tick state is stepping with "Server tick state is not stepping"
	make the server stop stepping
	unfreeze the server

	# Sprint the server and test
	make the server sprint for 10 seconds
	assert server's tick state is sprinting with "Server tick state is not sprinting"
	make the server stop sprinting

