test "line of sight":
	loop blocks between (spawn of world "world") and (spawn of world "world" ~ vector(0, 10, 0)):
		set {_block::%loop-block%} to type of loop-block
		set loop-block to air
	spawn pig at spawn of world "world"
	set {_pig1} to last spawned entity
	spawn pig at ((spawn of world "world") ~ vector(0, 10, 0)):
		assert pig has line of sight to {_pig1} with "Pigs should have line of sight to each other 1"
		assert {_pig1} has line of sight to pig with "Pigs should have line of sight to each other 2"
		set block at ((spawn of world "world") ~ vector(0, 5, 0)) to stone
		assert pig has no line of sight to {_pig1} with "Pigs should not have line of sight to each other 1"
		assert {_pig1} has no line of sight to pig with "Pigs should not have line of sight to each other 2"
		delete pig
	delete entity within {_pig1}
	loop blocks between (spawn of world "world") and (spawn of world "world" ~ vector(0, 10, 0)):
		set loop-block to {_block::%loop-block%}
