test "loot table condition":
	spawn a pig at spawn of "world"
	set {_pig} to last spawned pig

	assert {_pig} has loot table with "default has loot table failed"

	clear loot table of {_pig}
	assert {_pig} doesn't have a loot table with "pig still has loot table after clearing loot table"

	set loot table of {_pig} to "minecraft:entities/cow"
	assert {_pig} has loot table with "simple has loot table failed"

	set loot table of {_pig} to "bleh blah bluh" parsed as loot table
	assert {_pig} doesn't have a loot table with "pig still has loot table after setting invalid loot table"

	clear {_pig}

	set block at spawn of "world" to chest
	set {_block} to block at spawn of "world"

	assert {_block} doesn't have loot table with "has loot table without setting it"

	set loot table of {_block} to "minecraft:chests/simple_dungeon"
	assert {_block} has loot table with "simple has loot table failed"

	clear loot table of {_block}
	assert {_block} doesn't have a loot table with "block still has loot table after clearing loot table"

	set loot table of {_block} to "bleh blah bluh" parsed as loot table
	assert {_block} doesn't have a loot table with "block still has loot table after setting invalid loot table"
