test "CondIsInvulnerable" when running minecraft "1.20.6":
	assert creative is invulnerable with "Creative mode should be invulnerable"
	assert survival is not invulnerable with "Survival mode should not be invulnerable"

test "CondIsInvulnerable":
	spawn armor stand at spawn of world "world":
		make entity invulnerable
		assert entity is invulnerable with "Entity should be invulnerable"
		make entity vulnerable
		assert entity is vulnerable with "Entity should be vulnerable"
		delete entity
	set {_} to {_}
	assert {_} is vulnerable with "Empty variable should be vulnerable"