test "method exists":
	assert method "java.lang.String##length()" exists with "Existing method was not found"
	assert method "java.lang.String##notReal()" doesn't exist with "Fake method was found"
	assert method "java.lang.SuperFakeClass##notReal()" doesn't exist with "Fake method was found"
	assert method "java.lang.String##indexOf(java.lang.String)" exists with "Existing method with args was not found"
	assert method "java.lang.String##replace(java.lang.CharSequence,java.lang.CharSequence)" exists with "Existing method with multiple args not found"
