test "loot context":

	set {_context} to a new loot context at spawn of "world"
	assert loot location of {_context} is spawn of "world" with "loot context location failed"

	spawn a pig at spawn of "world"
	set {_pig} to last spawned pig

	set {_context} to a new loot context at spawn of "world":
		assert loot context is set with "loot context not set"
		set loot entity to {_pig}
		set loot luck value to 10

	assert loot entity of {_context} is {_pig} with "loot context entity failed"
	assert loot luck value of {_context} is 10 with "simple loot context luck value failed"

	clear {_pig}

	set {_context} to a new loot context at spawn of "world":
		set loot luck value to -1
	assert the loot luck of {_context} is -1 with "negative loot luck set failed"

	set {_context} to a new loot context at spawn of "world":
		set loot luck value to 2
	assert the loot luck of {_context} is 2 with "existing loot luck set failed"

	set {_context} to a new loot context at spawn of "world":
		set loot luck value to 3.3
	assert the loot luck of {_context} is 3.3 with "decimal loot luck set failed"

	set {_context} to a new loot context at spawn of "world":
		set loot luck value to 3.999
	assert the loot luck of {_context} is 3.999 with "close decimal loot luck set failed"

	set {_context} to a new loot context at spawn of "world":
		set loot luck value to -3.3
	assert the loot luck of {_context} is -3.3 with "negative decimal loot luck set failed"

	set {_context} to a new loot context at spawn of "world":
		set loot luck value to -3.999
	assert the loot luck of {_context} is -3.999 with "negative close decimal loot luck set failed"
