test "dusted stage" when running minecraft "1.20":
    set block 1 block under event-location to stone
    set block at event-location to suspicious gravel
    set {_block} to block at event-location

    set dusted stage of {_block} to 2
    assert dusted stage of {_block} is 2 with "Failed to set dusted stage to 2"

    set dusted stage of {_block} to 3
    assert dusted stage of {_block} is 3 with "Failed to set dusted stage to 3"

    set dusted stage of {_block} to 0
    assert dusted stage of {_block} is 0 with "Failed to reset dusted stage to 0"

    set block at {_block} to air
    set block 1 block under {_block} to air

test "Brushable Item" when running minecraft "1.20":
	set block 1 block under event-location to stone
	set block at event-location to suspicious gravel
	set {_block} to block at event-location

	set {_block}'s brushable item to gold nugget
	assert {_block}'s brushable item is gold nugget with "Failed to set brushable item to gold nugget"

	set {_block}'s brushable item to diamond
	assert {_block}'s brushable item is diamond with "Failed to set brushable item to diamond"

	set {_block}'s brushable item to air
	assert {_block}'s brushable item is air with "Failed to clear brushable item"
	set block at {_block} to air
	set block 1 block under {_block} to air
	
