test "angle":
	assert 90 degrees is 90 with "90 degrees is not 90"
	assert -10.5 degrees is -10.5 with "-10.5 degrees is not -10.5"
	assert 354698306983560 degrees is 354698306983560 with "354698306983560 degrees is not 354698306983560"

	assert pi radians is 180.0 degrees with "pi radians is not 180 degrees"
	assert 2 * pi radians is 360.0 degrees with "2pi radians is not 360 degrees"

	assert 180 degrees is pi radians with "180 degrees is not pi radians"
	assert 360 degrees is 2 * pi radians with "360 degrees is not 2pi radians"
