test "Dusted Stage" when running minecraft "1.20":
	set block at spawn of world "world" to suspicious gravel
    set {_block} to block at spawn of world "world"

	set dusted stage of {_block} to 2
	assert dusted stage of {_block} is 2 with "Failed to set dusted stage to 2"

	set dusted stage of {_block} to 3
	assert dusted stage of {_block} is 3 with "Failed to set dusted stage to 3"

	set dusted stage of {_block} to 0
	assert dusted stage of {_block} is 0 with "Failed to reset dusted stage to 0"

	set {_block} to air

test "Brushable Item" when running minecraft "1.20":
	set block at spawn of world "world" to suspicious gravel
	set {_block} to block at spawn of world "world"

	set brushable item of {_block} to gold nugget
	assert brushable item of {_block} is gold nugget with "Failed to set brushable item to gold nugget"

	set brushable item of {_block} to diamond
	assert brushable item of {_block} is diamond with "Failed to set brushable item to diamond"

	set brushable item of {_block} to air
	assert brushable item of {_block} is air with "Failed to clear brushable item"