test "item with enchantment glint" when running minecraft "1.20.5":

	# Expression %itemtype% with enchantment glint
	set {_glint1} to diamond with enchantment glint
	assert {_glint1} has enchantment glint override with "{_glint1} expected to have enchantment glint override set"
	assert enchantment glint of {_glint1} is true with "{_glint1} expected to have enchantment glint override set to true"
	set {_glint1} to {_glint1} without enchantment glint
	assert {_glint1} does not have enchantment glint override with "{_glint1} expected to not have enchantment glint override set"
	assert enchantment glint of {_glint1} is false with "{_glint1} expected to have enchantment glint override set to false"

	# Expression %itemtype%'s enchantment glint
	set {_glint2} to diamond
	set enchantment glint of {_glint2} to true
	assert {_glint2} has enchantment glint override with "{_glint2} expected to have enchantment glint override set"
	assert enchantment glint of {_glint2} is true with "{_glint2} expected to have enchantment glint override set to true"
	set enchantment glint of {_glint2} to false
	assert {_glint2} has enchantment glint override with "{_glint2} expected to have enchantment glint override set"
	assert enchantment glint of {_glint2} is false with "{_glint2} expected to have enchantment glint override set to false"
	clear enchantment glint of {_glint2}
	assert {_glint2} does not have enchantment glint override with "{_glint2} expected to not have enchantment glint override set"
	assert enchantment glint of {_glint2} is not set with "{_glint2} expected to have enchantment glint override cleared"
