test "lowest/highest solid block":

	# highest solid block
	set block at location(0.5, 250.5, 0.5, "world") to dirt
	set {_highest} to highest solid block at location(0.5, 0.5, 0.5, "world")
	assert type of {_highest} is dirt with "highest block is not dirt (got '%type of {_highest}%')"
	assert location of {_highest} is location(0.5, 250.5, 0.5, "world") with "highest block is not at 0.5,250.5,0.5 (got '%location of {_highest}%')"

	# lowest solid block
	set block at location(0.5, -64.5, 0.5, "world") to air
	set block at location(0.5, -63.5, 0.5, "world") to air
	set block at location(0.5, -62.5, 0.5, "world") to dirt
	set {_lowest} to lowest solid block at location(0.5, 0.5, 0.5, "world")
	assert type of {_lowest} is dirt with "lowest block is not dirt (got '%type of {_lowest}%')"
	assert location of {_lowest} is location(0.5, -62.5, 0.5, "world") with "lowest block is not at 0.5,-62.5,0.5 (got '%location of {_lowest}%')"

