local function expr_none_default(x: int = none) :: object:
	return {_x}

local function expr_unset_default(x: int = {_}) :: object:
	return {_x}

test "ExprNone":
	assert expr_none_default() is not set with "none default should leave the parameter unset"
	assert expr_none_default(1) is 1 with "provided function argument should override none default"
	assert expr_unset_default() is not set with "unset local default should leave the parameter unset"
