test "max stack":
	assert max stack size of diamond sword is 1 with "diamond sword max stack size failed"
	assert max stack size of bucket is 16 with "bucket max stack size failed"
	assert max stack size of dirt is 64 with "dirt max stack size failed"

test "max stack override - itemtype" when running minecraft "1.20.5":
	set {_item} to diamond
	set max stack size of {_item} to 32
	assert max stack size of {_item} is 32 with "diamond should have max stack size of 32"
	add 2 to max stack size of {_item}
	assert max stack size of {_item} is 34 with "diamond should have max stack size of 34"
	remove 4 from max stack size of {_item}
	assert max stack size of {_item} is 30 with "diamond should have max stack size of 30"
	reset max stack size of {_item}
	assert max stack size of {_item} is 64 with "diamond should have max stack size of 64"

	set {_item} to bucket
	set max stack size of {_item} to 24
	assert max stack size of {_item} is 24 with "bucket should have max stack size of 24"
	add 2 to max stack size of {_item}
	assert max stack size of {_item} is 26 with "bucket should have max stack size of 26"
	remove 4 from max stack size of {_item}
	assert max stack size of {_item} is 22 with "bucket should have max stack size of 22"
	reset max stack size of {_item}
	assert max stack size of {_item} is 16 with "bucket should have max stack size of 16"

	set {_item} to diamond sword
	set max stack size of {_item} to 16
	assert max stack size of {_item} is 16 with "diamond sword should have max stack size of 16"
	add 2 to max stack size of {_item}
	assert max stack size of {_item} is 18 with "diamond sword should have max stack size of 18"
	remove 4 from max stack size of {_item}
	assert max stack size of {_item} is 14 with "diamond sword should have max stack size of 14"
	reset max stack size of {_item}
	assert max stack size of {_item} is 1 with "diamond sword should have max stack size of 1"

test "max stack override - inventory":
	set {_inv} to a new chest inventory with 1 rows
	# Based on manual testing, max stack size of an inventory defaults to 99
	assert max stack size of {_inv} is 99 with "inventory should have max stack size of 99"
	set max stack size of {_inv} to 32
	assert max stack size of {_inv} is 32 with "inventory should have max stack size of 32"
	add 2 to max stack size of {_inv}
	assert max stack size of {_inv} is 34 with "inventory should have max stack size of 34"
	remove 4 from max stack size of {_inv}
	assert max stack size of {_inv} is 30 with "inventory should have max stack size of 30"
	reset max stack size of {_inv}
	assert max stack size of {_inv} is 99 with "inventory should have factory max stack size of 99"
