options:
	path: "../../../../../../src/test/skript/tests/"

test "enabled errors":
	set {_path} to {@path} + "misc/-reloadErrors.sk"
	enable script named {_path}
	assert last enabled errors contains "Can't understand this expression: 'blah'" with "Did not retrieve last enabled errors"

test "reloaded errors":
	set {_path} to {@path} + "misc/reloadErrors.sk"
	reload script named {_path}
	assert last reloaded errors contains "Can't understand this expression: 'blah'" with "Did not retrieve last reloaded errors"
	disable script named {_path}
