test "worldborder center":
	set {_border} to worldborder of world("world")
	assert worldborder center of {_border} is location(0, 0, 0, "world") with "default border center is not (0,0)"
	set worldborder center of {_border} to location(2, 0, 4, "world")
	assert worldborder center of {_border} is location(2, 0, 4, "world") with "failed to set border center"
	set worldborder center of {_border} to {_None}
	assert worldborder center of {_border} is location(2, 0, 4, "world") with "setting location of border to None moved border"
	set worldborder center of {_border} to location(31000000, 0, 0, "world")
	assert worldborder center of {_border} is location(29999984, 0, 0, "world") with "border center x-coord was not restricted to fit inside the world"
	set worldborder center of {_border} to location(0, 0, -31000000, "world")
	assert worldborder center of {_border} is location(0, 0, -29999984, "world") with "border center z-coord was not restricted to fit inside the world"
	reset worldborder center of {_border}
	assert worldborder center of {_border} is location(0, 0, 0, "world") with "failed to reset border center"