test "worldborder warning distance":
	set {_border} to worldborder of world("world")
	assert worldborder warning distance of {_border} is 5 with "Default worldborder warning distance is not 5"

	set worldborder warning distance of {_border} to 1
	assert worldborder warning distance of {_border} is 1 with "Failed to set worldborder warning distance"
	set worldborder warning distance of {_border} to {_None}
	assert worldborder warning distance of {_border} is 1 with "Setting worldborder warning distance to None changed the warning distance"

	add 1 to worldborder warning distance of {_border}
	assert worldborder warning distance of {_border} is 2 with "Failed adding to warning distance"
	add -1 to worldborder warning distance of {_border}
	assert worldborder warning distance of {_border} is 1 with "Failed adding negative integer to warning distance"
	add {_None} to worldborder warning distance of {_border}
	assert worldborder warning distance of {_border} is 1 with "Adding None to worldborder warning distance changed the warning distance"

	remove 1 from worldborder warning distance of {_border}
	assert worldborder warning distance of {_border} is 0 with "Failed removing from warning distance"
	remove -1 from worldborder warning distance of {_border}
	assert worldborder warning distance of {_border} is 1 with "Failed removing negative integer from warning distance"
	remove {_None} from worldborder warning distance of {_border}
	assert worldborder warning distance of {_border} is 1 with "Removing None from worldborder warning distance changed the warning distance"

	set worldborder warning distance of {_border} to -10
	assert worldborder warning distance of {_border} is 0 with "warning distance should was set to an integer less than 0"
	remove 1 from worldborder warning distance of {_border}
	assert worldborder warning distance of {_border} is 0 with "warning distance went below 0 when subtracting"

	reset worldborder warning distance of {_border}
	assert worldborder warning distance of {_border} is 5 with "Failed to reset border warning distance"