# No ExprBrushableDusted test, as changing the block's stage most likely takes a tick

test "Brushable Item" when running minecraft "1.20":
	set block 1 block under event-location to stone
	set block at event-location to suspicious gravel
	set {_block} to block at event-location

	set {_block}'s brushable item to gold nugget
	assert {_block}'s brushable item is gold nugget with "Failed to set brushable item to gold nugget"

	set {_block}'s brushable item to diamond
	assert {_block}'s brushable item is diamond with "Failed to set brushable item to diamond"

	set {_block}'s brushable item to air
	assert {_block}'s brushable item is air with "Failed to clear brushable item"
	set block at {_block} to air
	set block 1 block under {_block} to air