test "item with enchantment glint" when running minecraft "1.20.5":

	# with enchantment glint
	set {_item} to diamond with enchantment glint
	assert {_item} is forced to glint with "Item is expected to be forced to glint"
	clear enchantment glint override of {_item}
	assert {_item} has enchantment glint override with "Item is expected to have enchantment glint override set ##1"
	assert {_item} does not have enchantment glint override to fail with "Item is expected to have enchantment glint override set ##2"
	delete {_item}

	# without enchantment glint
	set {_item} to diamond without enchantment glint
	assert {_item} is forced to not glint with "Item is expected to be forced to not glint"
	assert {_item} has enchantment glint override with "Item is expected to have enchantment glint override set ##3"
	assert {_item} does not have enchantment glint override to fail with "Item is expected to have enchantment glint override set ##4"

	# edge cases
	assert {_null} is forced to glint to fail with "Condition 'item is forced to glint' expected to fail with non itemtypes ##1"
	assert {_null} is forced to not glint to fail with "Condition 'item is forced to glint' expected to fail with non itemtypes ##2"
	assert {_null} has enchantment glint override to fail with "Condition 'item has enchantment glint override' expected to fail with non itemtypes ##1"
	assert {_null} does not have enchantment glint override to fail with "Condition 'item has enchantment glint override' expected to fail with non itemtypes ##2"

