test "single value in variable":
	set {_num} to 1337
	assert number within {_num} is 1337 with "number within variable failed"
	suppress type hints
	assert string within {_num} is not set with "wrong type within variable returned a value"
	unsuppress type hints

test "multiple values in list":
	set {_values::*} to "something", 10, "test" and a zombie
	assert size of (strings within {_values::*}) is 2 with "strings within list failed"
