options:
	junit: "org.skriptlang.skript.test.tests.syntaxes.events.EvtWhitelistTest"

on player whitelist toggled:
	junit test is {@junit}
	name of event-offline player is "Njol"
	complete objective "listen for player whitelist toggled" for {@junit}

on player whitelist added:
	junit test is {@junit}
	name of event-offline player is "Njol"
	complete objective "listen for player whitelist added" for {@junit}

on player whitelist removed:
	junit test is {@junit}
	name of event-offline player is "Njol"
	complete objective "listen for player whitelist removed" for {@junit}
