options:
	test: "org.skriptlang.skript.test.tests.syntaxes.events.EntryContainerTest"

test "EntryContainerTest" when running JUnit:
	set {_tests::1} to "has entry"
	set {_tests::2} to "has multiple entry"
	ensure junit test {@test} completes {_tests::*}

test entry container:
	has entry:
		complete objective "has entry" for {@test}
	has multiple entry:
		set {entry-container-test::call-count} to 0
		add 1 to {entry-container-test::call-count}
	has multiple entry:
		add 1 to {entry-container-test::call-count}
		if {entry-container-test::call-count} is 2:
			complete objective "has multiple entry" for {@test}
