test "EvtBreedJUnit" when running JUnit:
	set {_tests::1} to "correct breeder"
	set {_tests::2} to "correct breeding mother"
	set {_tests::3} to "correct breeding father"
	set {_tests::4} to "correct bred child"
	set {_tests::5} to "item is carrot"

	ensure junit test "org.skriptlang.skript.test.tests.syntaxes.events.EvtBreedTest" completes {_tests::*}

on breed of pig:
	set {_test} to "org.skriptlang.skript.test.tests.syntaxes.events.EvtBreedTest"
	junit test is {_test}

	if breeder is player named "Efnilite":
		complete objective "correct breeder" for {_test}

	if breeding mother is pig named "mother":
		complete objective "correct breeding mother" for {_test}

	if breeding father is pig named "father":
		complete objective "correct breeding father" for {_test}

	if bred child is pig named "child":
		complete objective "correct bred child" for {_test}

	if event-item is a carrot:
		complete objective "item is carrot" for {_test}