options:
	EvtExplodeTest: "org.skriptlang.skript.test.tests.syntaxes.events.EvtExplodeTest"

test "EvtExplodeJUnit" when running JUnit:
	add "any explode" to {_tests::*}
	add "script explode" to {_tests::*}
	add "entity explode" to {_tests::*}

	ensure junit test {@EvtExplodeTest} completes {_tests::*}

on scripted explode:
	junit test is {@EvtExplodeTest}

	if event-location is set:
		complete objective "script explode" for {@EvtExplodeTest}

on pig explode:
	junit test is {@EvtExplodeTest}

	if event-entity is pig:
		complete objective "entity explode" for {@EvtExplodeTest}

on explode:
	junit test is {@EvtExplodeTest}

	complete objective "any explode" for {@EvtExplodeTest}
