options:
	test: "org.skriptlang.skript.test.tests.syntaxes.events.EvtFertilizeEggTest"

test "EvtFertilizeEggTest" when running Junit:
	add "fertilize egg event - general" to {_evt::*}
	add "fertilize egg event - specified entity" to {_evt::*}
	add "fertilize egg event - mother" to {_evt::*}
	add "fertilize egg event - father" to {_evt::*}
	add "fertilize egg event - breeder is player" to {_evt::*}
	add "fertilize egg event - item is slimeball" to {_evt::*}
	add "fertilize egg event - experience is 5" to {_evt::*}
	ensure junit test {@test} completes {_evt::*}

on fertilize egg:
	junit test is {@test}
	complete objective "fertilize egg event - general" for {@test}

on fertilize egg of frog:
	junit test is {@test}
	complete objective "fertilize egg event - specified entity" for {@test}
	breeding mother is frog
	complete objective "fertilize egg event - mother" for {@test}
	breeding father is frog
	complete objective "fertilize egg event - father" for {@test}
	if event-player is a player:
		complete objective "fertilize egg event - breeder is player" for {@test}
	if event-item is slimeball:
		complete objective "fertilize egg event - item is slimeball" for {@test}
	if event-experience is 5:
		complete objective "fertilize egg event - experience is 5" for {@test}
