options:
	junit: "org.skriptlang.skript.test.tests.syntaxes.events.EvtWhitelistTest"

test "EvtWhitelistTest" when running JUnit:
	# Server whitelist tests
	set {_test::113.1} to "listen for server whitelist toggled"
	set {_test::113.2} to "listen for server whitelist enabled"
	set {_test::113.3} to "listen for server whitelist disabled"

	# Player whitelist tests
	if running minecraft "1.20":
		set {_test::120.1} to "listen for player whitelist toggled"
		set {_test::120.2} to "listen for player whitelist added"
		set {_test::120.3} to "listen for player whitelist removed"

	ensure junit test {@junit} completes {_tests::*}


# Server whitelist events

on server whitelist toggled:
	junit test is {@junit}
	complete objective "listen for server whitelist toggled" for {@junit}

on server whitelist enabled:
	junit test is {@junit}
	the server will be whitelisted
	complete objective "listen for server whitelist enabled" for {@junit}

on server whitelist disabled:
	junit test is {@junit}
	the server will not be whitelisted
	complete objective "listen for server whitelist disabled" for {@junit}


# Player whitelist events

on player whitelist toggled:
	junit test is {@junit}
	name of event-offline player is "Njol"
	complete objective "listen for player whitelist toggled" for {@junit}

on player whitelist added:
	junit test is {@junit}
	name of event-offline player is "Njol"
	complete objective "listen for player whitelist added" for {@junit}

on player whitelist removed:
	junit test is {@junit}
	name of event-offline player is "Njol"
	complete objective "listen for player whitelist removed" for {@junit}
