test "SimpleAsyncJUnitTest" when running JUnit:
	ensure junit test "org.skriptlang.skript.test.tests.regression.SimpleAsyncJUnitTest" completes "sent message"

on broadcast:
	set {_test} to "org.skriptlang.skript.test.tests.regression.SimpleAsyncJUnitTest"
	junit test is {_test}

	assert broadcasted message is "Intentional broadcast!" with "broadcasted message was not 'Intentional broadcast!'"

	complete objective "sent message" for {_test}
