name: Generate documentation

inputs:
  docs_output_dir:
    description: "The directory to generate the documentation into"
    required: true
    type: string
  docs_repo_dir:
    description: "The documentation repository directory"
    required: true
    type: string
  docs_file_name:
    description: "The file name of the JSON docs file to update"
    required: true
    type: string
  skript_repo_dir:
    description: "The Skript repository directory"
    required: true
    type: string
  is_release:
    description: "Designates whether to generate release or nightly documentation"
    required: false
    default: false
    type: boolean

outputs:
  DOCS_CHANGED:
    description: "Whether the documentation has changed since the last push"
    value: ${{ steps.generate.outputs.DOCS_CHANGED }}

runs:
  using: 'composite'
  steps:
    - name: generate-docs
      id: generate
      shell: bash
      env:
        DOCS_OUTPUT_DIR: ${{ inputs.docs_output_dir }}
        DOCS_REPO_DIR: ${{ inputs.docs_repo_dir }}
        DOCS_FILE_NAME: ${{ inputs.docs_file_name }}
        SKRIPT_REPO_DIR: ${{ inputs.skript_repo_dir }}
        IS_RELEASE: ${{ inputs.is_release }}
        CLEANUP_PATTERN: ${{ inputs.cleanup_pattern }}
        GENERATE_JAVADOCS: ${{ inputs.generate_javadocs }}
      run: |
        # Generate docs.json from Skript repository
        export SKRIPT_DOCS_OUTPUT_DIR=$DOCS_OUTPUT_DIR
        cd $SKRIPT_REPO_DIR
        if [[ "${IS_RELEASE}" == "true" ]]; then
          ./gradlew genReleaseDocs javadoc
        elif [[ "${GENERATE_JAVADOCS}" == "true" ]]; then
          ./gradlew genNightlyDocs javadoc
        else
          ./gradlew genNightlyDocs
        fi

        # Sanitize expected existing file name
        src_file="${DOCS_FILE_NAME//\//-}.json"

        # Compare generated file vs existing file for changes
        cd $DOCS_OUTPUT_DIR
        docs_changed=false
        if [[ -f ${src_file} ]]; then
          diff -qb ${src_file} Skript-docs.json || diff_exit_code=$?
          # If diff exits with exit code 1, that means there were some differences
          if [[ ${diff_exit_code} -eq 1 ]]; then
            docs_changed=true
          fi
        else # generating these docs for the first time
          docs_changed=true
        fi

        # Record status
        if [[ ${docs_changed} == "true" ]]; then
          echo "Documentation has changed since last push"
          echo "DOCS_CHANGED=true" >> $GITHUB_OUTPUT
        else
          echo "Documentation hasn't changed since last push"
          exit
        fi

        # Replace existing file with generated file
        mv Skript-docs.json ${src_file}
