test "breedable" when running minecraft "1.16.5":
	delete all chickens
	set {_spawn} to spawn of world "world"
	spawn baby chicken at {_spawn}
	set {_chicken} to last spawned chicken
	assert {_chicken} can't breed with "Chicken could breed before growing up"
	make {_chicken} breedable
	assert {_chicken} can breed with "Chicken can't breed after growing up"
	make {_chicken} non-breedable
	assert {_chicken} can't breed with "Chicken can breed after growing up and preventing"
	delete all chickens
