test "left handedness":
	spawn skeleton at test-location:
		make entity right handed
		assert entity is not left handed with "zombie is left handed after being made right handed"
		assert entity is right handed with "zombie is not right handed after being made right handed"
		make entity left handed
		assert entity is not right handed with "zombie is right handed after being made left handed"
		assert entity is left handed with "zombie is not left handed after being made left handed"
		make entity left handed
		assert entity is left handed with "zombie is not left handed after being made left handed again"
		delete entity

test "mannequin handedness" when running minecraft "1.21.9":
	spawn a mannequin at test-location:
		set {_entity} to entity

	make {_entity} right handed
	assert {_entity} is right handed with "Mannequin should be right handed"
	make {_entity} left handed
	assert {_entity} is left handed with "Mannequin should be left handed"
