test "locking age" when running minecraft "1.16.5":
	delete all pigs
	set {_spawn} to spawn of world "world"
	spawn baby pig at {_spawn}
	set {_pig} to last spawned pig
	assert {_pig} can age with "Baby pig can't age before locking Test1"
	lock age of {_pig}
	assert {_pig} can't age with "Baby pig can still age after locking"
	unlock age of {_pig}
	assert {_pig} can age with "Baby pig can't age after unlocking Test2"
	delete all pigs
