test "toggle effect":
  set {_isToggled} to false
  assert {_isToggled} is false with "{_isToggled} should be set to false"
  toggle {_isToggled}
  assert {_isToggled} is true with "{_isToggled} should be toggled to true"
  set {_toggle::*} to false, false and false
  assert {_toggle::1} is false with "{_toggle::1} should be set to false"
  assert {_toggle::2} is false with "{_toggle::2} should be set to false"
  assert {_toggle::3} is false with "{_toggle::3} should be set to false"
  toggle {_toggle::*}
  assert {_toggle::1} is true with "{_toggle::1} should be toggled to true"
  assert {_toggle::2} is true with "{_toggle::2} should be toggled to true"
  assert {_toggle::3} is true with "{_toggle::3} should be toggled to true"
  assert inverse of {_isToggled} is false with "{_isToggled} should be toggled to false"

  set {_block} to block at location(10, 10, 10, world "world")
  set {_list::*} to true and {_block}
  toggle {_list::*}
  assert {_list::1} is false with "{_list::1} should be set to false"
  assert amount of {_list::*} is 2 with "{_list::*} should be set to false and {_block}"
