function {@function}) :: boolean:
	return true

options:
	function: foo(

function local() :: number:
	return 1

local function local() :: number:
	return 2

local function bar() :: boolean:
	return true

local function _blob() :: string:
	return "blub"

test "functions":
	assert foo() is true with "function return type failed"
	assert local() is not 1 with "global function parsed before local function"
	assert bar() is true with "local function didn't execute correctly"
	assert _blob() is "blub" with "function that starts with underscore didn't execute correctly"

using local variable type hints

parse:
	results: {StructFunction::hints::1::*}
	code:
		function hint_test_1(x: number):
			set {_a} to {_x} in lowercase

parse:
	results: {StructFunction::hints::2::*}
	code:
		function hint_test_2(x: numbers):
			set {_a::*} to {_x::*} in lowercase

local function type_hint_argument_test(number: number):
	stop

test "function structure type hints":
	assert {StructFunction::hints::1::*} is "Expected variable '{_x}' to be a text, but it is a number" with "Hint failed (%{StructFunction::hints::1::*}%)"
	assert {StructFunction::hints::2::*} is "Expected variable '{_x::*}' to be a text, but it is a number" with "Hint failed (%{StructFunction::hints::2::*}%)"
	set {_number} to true
	parse:
		type_hint_argument_test({_number})
	assert the first element of the last parse logs is set # contains "The function 'type_hint_argument_test(boolean)' does not exist." (NEEDS FIXING)

local function list_argument_single_default(x: texts="hey") :: texts:
    return {_x::*}

test "function list argument with a single default":
	assert list_argument_single_default() = "hey"

local function literal_test(x: entity type):
	stop
local function literal_test_projectile(x: entity):
	stop

test "literal type parsing":
	parse:
		literal_test(firework)
	assert last parse logs is not set

	spawn an arrow at test-location:
		set {_entity} to entity
		parse:
			literal_test_projectile(projectile)
	assert last parse logs are not set
	clear entity within {_entity}

using delayed functions

local function delayed_returning_function() :: integer:
	wait a tick
	return 1

test "delayed function return":
	parse:
		delayed_returning_function()
	assert last parse logs is not set
	assert delayed_returning_function() is 1 with "delayed function failed"

local function repeated_delayed_function(input: integer) :: integer:
	wait a tick
	return {_input}

test "repeated delayed functions":
	parse:
		repeated_delayed_function(0)
	assert last parse logs is not set
	assert repeated_delayed_function(1) is 1 with "repeated delayed function failed"
	assert repeated_delayed_function(2) is 2 with "repeated delayed function failed"
	assert repeated_delayed_function(3) is 3 with "repeated delayed function failed"

local function delayed_return_locals() :: integer:
	set {_inside.before} to 1
	wait a tick
	set {_inside.after} to 2
	return 3

test "delayed function locals":
	parse:
		delayed_return_locals()
	assert last parse logs is not set
	set {_outside.before} to 0
	assert delayed_return_locals() is 3 with "delayed locals failed"
	assert {_outside.before} is 0 with "delayed function forgot call site locals"
	assert {_inside.before} isn't set with "delayed function bleeds locals"
	assert {_inside.after} isn't set with "delayed function bleeds locals"

local function delayed_no_return():
	wait 10 ticks
	set {-test.delayed_no_return} to true

test "no return delayed runs later":
	parse:
		delayed_no_return()
	assert last parse logs is not set
	delete {-test.delayed_no_return}
	delayed_no_return()
	assert {-test.delayed_no_return} isn't set with "waited for delayed function with no return value"

local function nested_delayed_one() :: integer:
	wait a tick
	return nested_delayed_two()

local function nested_delayed_two() :: integer:
	wait a tick
	return 2

test "nested delayed functions":
	parse:
		nested_delayed_one()
		nested_delayed_two()
	assert last parse logs is not set
	assert nested_delayed_one() is 2 with "nested delayed functions don't work"

local function nested_delayed_dirty_one() :: integer:
	wait a tick
	add 1 to {-test.nested_delayed_dirty}
	return nested_delayed_dirty_two()

local function nested_delayed_dirty_two() :: integer:
	wait a tick
	add 1 to {-test.nested_delayed_dirty}
	return {-test.nested_delayed_dirty}

test "delayed return value re-evaluation":
	parse:
		nested_delayed_dirty_one()
		nested_delayed_dirty_two()
	assert last parse logs is not set
	delete {-test.nested_delayed_dirty}
	nested_delayed_dirty_one()
	assert {-test.nested_delayed_dirty} is 2 with "Incorrect call count"
