using example feature
using fizz buzz

test "using":
	assert the current script is using "example feature" with "using feature failed"
	assert the current script is using "fizz buzz" with "using exact failed"
	assert the current script is using "fizzbuzz" with "using other pattern failed"
	assert the current script is using "test" with "using codename failed"
	assert the current script is using "testing" with "using alt pattern failed"
	assert the current script is not using "foo bar" with "using not present failed"
