using local variable type hints

options:
	command: skriptcommand

parse:
	results: {-StructCommand::args::1::*}
	code:
		command /args_test_1 <x:number> <x:number>:
			trigger:
				stop

parse:
	results: {-StructCommand::hints::1::*}
	code:
		command /hint_test_1 <x:number>:
			trigger:
				set {_a} to {_x} in lowercase

parse:
	results: {-StructCommand::hints::2::*}
	code:
		command /hint_test_2 <x:numbers>:
			trigger:
				set {_a::*} to {_x::*} in lowercase

command /test-subcommand <number>:
	subcommand <number>:
		trigger:
			set {-test-subcommand} to argument 1 - argument 2
	trigger:
		set {-test-subcommand} to arg-1

command /test-args-plural <x: numbers>:
	trigger:
		set {-test-args-plural::*} to {_x::*}

command {@command} <text> [<text>] [<itemtype = %dirt named "steve"%>]:
	trigger:
		set {_arg1} to arg-1
		assert {_arg1} is "taco" with "arg-1 test failed (got '%{_arg1}%')"
		set {_arg2} to arg-2
		assert {_arg2} is not set with "arg-2 test failed (got '%{_arg2}%')"
		set {_arg3} to arg-3
		assert {_arg3} is dirt named "steve" with "arg-3 test failed (got '%{_arg3}%')"

command //somecommand [<text>]:
	trigger:
		set {_arg1} to arg-1
		if {_arg1} is set:
			assert {_arg1} is "burrito is tasty" with "arg-1 is 'burrito is tasty' test failed (got '%{_arg1}%')"

# see https://github.com/SkriptLang/Skript/pull/6286
command /commandtest <string="player">:
	trigger:
		stop

test "StructCommand":
	# parsing
	assert {-StructCommand::args::1::*} is "The argument name 'x' was already used."
	# parsing type hints
	assert {-StructCommand::hints::1::*} is "Expected variable '{_x}' to be a text, but it is a number" with "Hint failed (%{StructCommand::hints::1::*}%)"
	assert {-StructCommand::hints::2::*} is "Expected variable '{_x::*}' to be a text, but it is a number" with "Hint failed (%{StructCommand::hints::2::*}%)"

	# execution
	execute command "test-subcommand 10"
	assert {-test-subcommand} is 10 with "root command execution failed"
	execute command "test-subcommand 10 5"
	assert {-test-subcommand} is 5 with "subcommand command execution failed"

	execute command "test-args-plural 10"
	assert {-test-args-plural::*} is 10 with "single input to plural args did not work"
	execute command "test-args-plural 10 and 2"
	assert {-test-args-plural::*} is 10 and 2 with "plural input to plural args did not work"

	execute command "skriptcommand taco"
	execute command "//somecommand burrito is tasty"
