using local variable type hints

options:
	command: skriptcommand

# expect error for missing trigger given no subcommands
parse:
	results: {-StructCommand::entries::1::*}
	code:
		command /entries_test_1:

# expect error for invalid executable by for subcommand
parse:
	results: {-StructCommand::entries::2::*}
	code:
		command /entries_test_2:
			executable by: players
			trigger:
				stop
			subcommand test:
				executable by: console
				trigger:
					stop

# expect error for invalid subcommand and subsequently missing trigger (given no valid subcommands)
parse:
	results: {-StructCommand::entries::3::*}
	code:
		command /entries_test_3:
			subcommand test:

# expect error for duplicate argument names
parse:
	results: {-StructCommand::args::1::*}
	code:
		command /args_test_1 <x:number> <x:number>:
			trigger:
				stop

# expect error for type not supporting range
parse:
	results: {-StructCommand::args::2::*}
	code:
		command /args_test_2 <x: text between "hello" and "world">:
			trigger:
				stop

# expect no errors
parse:
	results: {-StructCommand::args::3::*}
	code:
		command /args_test_3 <x: number above 5> <y: number below 5> <z: number between 5 and 5>:
			trigger:
				stop

# expect error that only single number arguments support ranged
parse:
	results: {-StructCommand::args::4::*}
	code:
		command /args_test_4 <x: numbers above 5>:
			trigger:
				stop

# expect error that {_x} is not a text
parse:
	results: {-StructCommand::hints::1::*}
	code:
		command /hint_test_1 <x:number>:
			trigger:
				set {_a} to {_x} in lowercase

# expect error that {_x::*} is not a text
parse:
	results: {-StructCommand::hints::2::*}
	code:
		command /hint_test_2 <x:numbers>:
			trigger:
				set {_a::*} to {_x::*} in lowercase

command /structcommand:
	aliases: /structcommand2
	description: This is the description
	usage: "This is the usage"
	permission: command.structcommand
	trigger:
		stop

command /test-subcommand <number>:
	subcommand <number>:
		trigger:
			set {-test-subcommand} to argument 1 - argument 2
	trigger:
		set {-test-subcommand} to arg-1

command /test-args-plural <x: numbers>:
	trigger:
		set {-test-args-plural::*} to {_x::*}

command /test-args-ranged <x: number above 5 and below 10>:
	trigger:
		set {-test-args-ranged::*} to {_x}

command {@command} <text> [<text>] [<itemtype = %dirt named "steve"%>]:
	trigger:
		set {-test-{@command}::arg1} to arg-1
		set {-test-{@command}::arg2} to arg-2
		set {-test-{@command}::arg3} to arg-3

command //somecommand [<text>]:
	trigger:
		set {-test-somecommand::arg1} to arg-1

# see https://github.com/SkriptLang/Skript/pull/6286
command /commandtest <string="player">:
	trigger:
		stop

test "StructCommand":
	# parsing
	set {_error_missing_trigger} to "You must have a 'trigger' entry if there are no subcommands!"
	assert {-StructCommand::entries::1::*} is {_error_missing_trigger}
	assert {-StructCommand::entries::2::*} is "It is not possible to restrict execution to the console as the parent command is only executable by players."
	assert {-StructCommand::entries::3::*} is {_error_missing_trigger} and {_error_missing_trigger}
	assert {-StructCommand::args::1::*} is "The argument name 'x' was already used."
	assert {-StructCommand::args::2::*} is "text arguments do not support minimum or maximum values."
	assert {-StructCommand::args::3::*} is not set
	assert {-StructCommand::args::4::*} is "Only single number arguments support minimum or maximum values."
	# parsing type hints
	assert {-StructCommand::hints::1::*} is "Expected variable '{_x}' to be a text, but it is a number" with "Hint failed (%{StructCommand::hints::1::*}%)"
	assert {-StructCommand::hints::2::*} is "Expected variable '{_x::*}' to be a text, but it is a number" with "Hint failed (%{StructCommand::hints::2::*}%)"

	# entry validation
	assert the main command name of the command "structcommand" is "structcommand"
	assert the description of the command "structcommand" is "This is the description"
	assert the label of the command "structcommand" is "structcommand"
	#assert the usage of the command "structcommand" is "This is the usage"
	assert the aliases of the command "structcommand" are "structcommand2" and "skript:structcommand2"
	#assert the permission of the command "structcommand" is "skript.structcommand"
	assert the plugin of the command "structcommand" is "Skript"

	# execution
	execute command "test-subcommand 10"
	assert {-test-subcommand} is 10 with "root command execution failed"
	execute command "test-subcommand 10 5"
	assert {-test-subcommand} is 5 with "subcommand command execution failed"

	execute command "test-args-plural 10"
	assert {-test-args-plural::*} is 10 with "single input to plural args did not work"
	execute command "test-args-plural 10 and 2"
	assert {-test-args-plural::*} is 10 and 2 with "plural input to plural args did not work"

	execute command "test-args-ranged 6"
	assert {-test-args-ranged::*} is 6 with "argument in range was not accepted"
	execute command "test-args-ranged 4"
	assert {-test-args-ranged::*} is 6 with "argument below range was accepted"
	execute command "test-args-ranged 11"
	assert {-test-args-ranged::*} is 6 with "argument above range was accepted"

	execute command "{@command} taco"
	assert {-test-{@command}::arg1} is "taco" with "arg-1 test failed"
	assert {-test-{@command}::arg2} is not set with "arg-2 test failed"
	assert {-test-{@command}::arg3} is dirt named "steve" with "arg-3 test failed"

	# On some older versions (1.21.4, TBD), '//somecommand' does not work through console.
	# This appears to be some sort of server issue.
	execute command "skript:/somecommand burrito is tasty"
	assert {-test-somecommand::arg1} is "burrito is tasty" with "arg-1 is 'burrito is tasty' test failed"
