local function esf(x: int):: int:
	return 1

local function esf(x: string):: int:
	return 2

local function esf(x: objects):: int:
	return 3

local function esf_two(x: int, y: int):: int:
	return 4

local function esf_void(x: int):
	stop

test "function section result":
	set {_x} to result of function esf with arguments:
		x set to 1
	assert {_x} = 1

	set {_x} to result of function esf with arguments:
		x set to "hey"
	assert {_x} = 2

	set {_x} to result of function esf with arguments:
		x set to 1 and 2
	assert {_x} = 3

	set {_x} to result of function esf with arguments:
		x set to 1, 2, 3, {_a}, {_b::*}
	assert {_x} = 3

	parse:
		set {_x} to result of function esf with arguments:
			x set to {_y}
	assert first element of last parse logs is set

	set {_y} to 3
	set {_x} to result of function esf with arguments:
		x set to integer within {_y}
	assert {_x} = 1

	parse:
		set {_x} to result of function esf_two with arguments:
			x set to firework
	assert first element of last parse logs contains "The function 'esf_two(x: item type)' does not exist"

	parse:
		set {_x} to result of function esf with arguments:
			x set to agasgasfgadsfg
	assert first element of last parse logs contains "Can't understand the argument for the parameter"

	set {_x} to result of function esf_two with arguments:
		x set to 1
		y set to 2
	assert {_x} = 4

	set {_x} to result of function esf_two with arguments:
		y set to 2
		x set to 1
	assert {_x} = 4

	parse:
		set {_x} to result of function esf_void with arguments:
			x set to 1
	assert first element of last parse logs contains "The function 'esf_void' does not return anything"

options:
	path: "../../../../../../src/test/skript/tests/syntaxes/expressions/"
	misc: "../../../../../../src/test/skript/tests/misc/"

	# Princess test script is in another castle, Mario!
	# paths are relativised to the /scripts/ directory
	# but we are loading these scripts from the test folder :(

using script reflection

function testExprResult0() :: boolean:
	return true

local function testExprResult1() :: boolean:
	return true

test "result of functions":
	set {_function} to function "testExprResult0()"
	set {_result} to result of {_function}
	assert {_result} exists with "function didn't run"
	assert {_result} is true with "function didn't return correctly"
	delete {_result}

	set {_function} to function "testExprResult1()"
	set {_result} to result of {_function}
	assert {_result} exists with "function didn't run"
	assert {_result} is true with "function didn't return correctly"
	delete {_result}

test "result of external functions":
	set {_script} to the script named {@misc} + "dummy.sk"
	set {_function} to function "testDummy()" from {_script}
	assert {_function} exists with "function wasn't found"
	set {_result} to result of {_function}
	assert {_result} exists with "function didn't run"
	assert {_result} is true with "function didn't return correctly"
	delete {_result}

	set {_script} to the script named {@path} + "ExprFunction.sk"

	set {_function} to function "testExprFunction1()" from {_script}
	assert {_function} exists with "function wasn't found"
	set {_result} to result of {_function}
	assert {_result} exists with "function didn't run"
	assert {_result} is true with "function didn't return correctly"
	delete {_result}

	set {_function} to function "testExprFunction2()" from {_script}
	assert {_function} exists with "function wasn't found"
	set {_result} to result of {_function} with arguments "hello" and 0
	assert {_result} exists with "function didn't run"
	assert {_result} is false with "function didn't return correctly"
	set {_result} to result of {_function} with arguments "hello" and 3
	assert {_result} is false with "function didn't return correctly"
	set {_result} to result of {_function} with arguments "hello" and 5
	assert {_result} is true with "function didn't return correctly"
	delete {_result}
