name: Setup documentation environment

inputs:
  docs_deploy_key: 
    description: "Deploy key for the skript-docs repo"
    required: true
    type: string
  docs_output_dir:
    description: "The directory to generate the documentation into"

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - run: chmod +x ./skript/gradlew
    - uses: actions/checkout@v3
      with:
          submodules: recursive
          path: skript
    - uses: actions/checkout@v3
      with:
          repository: 'SkriptLang/skript-docs'
          path: skript-docs
          ssh-key: ${{ inputs.docs_deploy_key }}
    - shell: bash
      env:
        DOCS_DEPLOY_KEY: ${{ inputs.docs_deploy_key }}
        DOCS_OUTPUT_DIR: ${{ inputs.docs_output_dir }}
      run: |
        eval `ssh-agent`
        rm -r ${DOCS_OUTPUT_DIR}/* || true
        echo "$DOCS_DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
        mkdir ~/.ssh
        ssh-keyscan www.github.com >> ~/.ssh/known_hosts
